version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    depends_on:
      db:
        condition: service_healthy      

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - 8080:80
    tty: true    
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD",  "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 9    

networks:
  node-network:
    driver: bridge